import Connect from "@/lib/components/Connect";
import Head from "next/head";
import { useConnect, useAccount, useBalance } from "wagmi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cosmic Chicken</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Connect />
      </main>
    </>
  );
}
